# Import specific functions/classes from the utils module
from pysmartdatamodels.utils.common_utils import (
    create_context,
    extract_datamodel_from_raw_url,
    extract_subject_from_raw_url,
    generate_random_string,
    is_metadata_properly_reported,
    is_metadata_existed,
    is_url_existed,
    message_after_check_schema,
    normalized2keyvalues_v2,
    open_jsonref,
    open_yaml,
    parse_payload_v2,
    parse_property2ngsild_example,
    parse_yamlDict,
    schema_output_sum
)

# Import the main API functions so they're reachable from the top-level
# package (`from pysmartdatamodels import generate_sql_schema`), not just
# via the `pysmartdatamodels.pysmartdatamodels` submodule.
from pysmartdatamodels.pysmartdatamodels import (
    attributes_datamodel,
    datamodel_repolink,
    datamodels_subject,
    datatype_attribute,
    description_attribute,
    generate_draft_schema,
    generate_sql_schema,
    geojson_features_example_generator,
    identify_or_draft_datamodel,
    load_all_attributes,
    load_all_datamodels,
    list_all_datamodels,
    list_all_subjects,
    list_datamodel_metadata,
    look_for_datamodel,
    model_attribute,
    ngsi_datatype_attribute,
    ngsi_ld_example_generator,
    ngsi_ld_keyvalue_example_generator,
    print_datamodel,
    subject_for_datamodel,
    subject_repolink,
    units_attribute,
    update_broker,
    update_data,
    validate_data_model_schema,
    validate_dcat_ap_distribution_sdm,
    validate_payload,
)

# Define what gets imported when using `from pysmartdatamodels import *`
__all__ = [
    'attributes_datamodel',
    'datamodel_repolink',
    'datamodels_subject',
    'datatype_attribute',
    'description_attribute',
    'generate_draft_schema',
    'generate_sql_schema',
    'geojson_features_example_generator',
    'identify_or_draft_datamodel',
    'load_all_attributes',
    'load_all_datamodels',
    'list_all_datamodels',
    'list_all_subjects',
    'list_datamodel_metadata',
    'look_for_datamodel',
    'model_attribute',
    'ngsi_datatype_attribute',
    'ngsi_ld_example_generator',
    'ngsi_ld_keyvalue_example_generator',
    'print_datamodel',
    'subject_for_datamodel',
    'subject_repolink',
    'units_attribute',
    'update_broker',
    'update_data',
    'validate_data_model_schema',
    'validate_dcat_ap_distribution_sdm',
    'validate_payload'
]